spring.datasource.url=jdbc:postgresql://localhost:5432/diagramdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.auto_quote_keyword=true
spring.flyway.enabled=false
server.port=8080
jwt.secret=TuClaveSecretaMuyLargaParaFirmarTokensJWTCon256BitsMinimo
jwt.expiration=3600000