CREATE TABLE IF NOT EXISTS cliente (
    id UUID PRIMARY KEY NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    fechaRegistro DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS pedido (
    id UUID PRIMARY KEY NOT NULL,
    fechaPedido DATE NOT NULL,
    total NUMERIC(19,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS producto (
    id UUID PRIMARY KEY NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    precio NUMERIC(19,2) NOT NULL,
    stock INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS factura (
    id UUID PRIMARY KEY NOT NULL,
    fechaFactura DATE NOT NULL,
    monto NUMERIC(19,2) NOT NULL
);

