CREATE TABLE IF NOT EXISTS "user" (
    id UUID PRIMARY KEY NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    createdAt DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "order" (
    id UUID PRIMARY KEY NOT NULL UNIQUE,
    orderDate DATE NOT NULL,
    totalAmount NUMERIC(19,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
    id UUID PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(19,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
    id UUID PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE
);

